### ISSUE TITLE
Question regarding decentralized-exchange-ink contract source code

### ISSUE THREAD

**Issue by Retamogordo** [TomaszWaszczyk/ink-automated-market-maker#8]
Hi,
thank you for this great tutorial.
There is an aspect, though, I'm trying to wrap my head around of,
namely what is the difference between 
```rust
estimate_swap_token1_for_given_token1
```
and 
```
estimate_swap_token1_for_given_token2
```
?
At first glance the only difference is that the second function has the additional check 
```rust
if amount_token_2 == self.pool_total_token2 {
    return Err(Error::PoolDepleted("Pool depleted".to_string()));
}
```
and this line 
```rust
let amount_token1 = self.pool_total_token2 - token2_after;
```

which in the first function looks:
```rust
let amount_token2 = self.pool_total_token2 - token2_after;
```
So why the name of the token in the first function refers to token 1 rather than token 2 ?
As far as I could guess from this description in the tutorial:
[tutorial](https://polkadot.study/tutorials/decentralized-exchange-ink/implementation)
"
The function estimate_swap_token1_for_given_token2 takes a balance amount of token1 as input and estimates the corresponding amount of token1 that the user needs to swap in order to receive a given amount of token2. It considers the pool's liquidity and trading fee, and returns the estimated amount of token1 as a result.
"
,
```estimate_swap_token1_for_given_token2``` is meant to take token2 as input parameter rather than token1 ?

**Comment by TomaszWaszczyk** [comment]
Thanks for the comment. You could have **right**, currently I work on UI and when will release it will be much easier to find/debug/make more consistency with this kind of bugs.

> There is an aspect, though, I'm trying to wrap my head around of,
> namely what is the difference between
> 
> estimate_swap_token1_for_given_token1
> 
> and
> 
> estimate_swap_token1_for_given_token2

The idea is slippage, it is a preparation for real issue in AMM that is slippage of the price - slippage on token1 side and token2 side. For the sake of simplicity I did not implement slippage mechanism, but those two functions is a preparation for that. While having UI would be easier to debug and practice with the source code.

**Comment by Retamogordo** [comment]
Thanks, I didn't realize the tutorial was under construction.

**Comment by TomaszWaszczyk** [comment]
@Retamogordo  Idea was to deliver it simply, implementation slippage could complicate things without any value and will result with the much more complicated (and of course take much more time to deliver).

Take into consideration that you can fork and improve the code like you want.
